name: Test Different Action

on:
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Action
        uses: actions/github-script@v7
        with:
          script: |
            console.log("Hello from GitHub Script!");