name: Update READMEs on YAML Change

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run on'
        required: true
        default: 'main'

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.18.0' # Adjust as needed

      - name: Check for YAML Changes
        id: check_yaml
        run: |
          changed_files=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | jq -r '.[].filename')
          if [[ "$changed_files" == *'your_yaml_file.yaml'* ]]; then
            echo "yaml_changed=true" >> $GITHUB_OUTPUT
          else
            echo "yaml_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Go Code
        if: steps.check_yaml.outputs.yaml_changed == 'true'
        run: |
          cd generator
          go run readme_app.go

      - name: Commit and Push Changes
        if: steps.check_yaml.outputs.yaml_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.head.ref }}
          force: true

      - name: Setup GitHub CLI
        if: steps.check_yaml.outputs.yaml_changed == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            await exec.exec('sudo apt-get update')
            await exec.exec('sudo apt-get install -y gh')
          retries: 2

      - name: Add Comment to PR
        if: steps.check_yaml.outputs.yaml_changed == 'true'
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Automated README updates have been pushed to this PR based on the changes to your_yaml_file.yaml."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}